const DATA_ACCESS = {
  administrador: ['dashboard', 'schools', 'network', 'inventory', 'ctc', 'calls', 'cars', 'supervision', 'contacts', 'calendar', 'satisfaction', 'satisfaction-online', 'internal', 'reports', 'profiles', 'quality', 'admin'],
  supervisao: ['dashboard', 'schools', 'supervision', 'contacts', 'calendar', 'reports'],
  'tecnicos ctc': ['dashboard', 'schools', 'network', 'inventory', 'ctc', 'calls', 'cars', 'supervision', 'contacts', 'calendar', 'internal', 'reports', 'profiles', 'quality'],
  setec: ['dashboard', 'schools', 'network', 'inventory', 'ctc', 'calls', 'contacts', 'cars', 'reports'],
  seintec: ['dashboard', 'schools', 'network', 'inventory', 'ctc', 'calls', 'cars', 'supervision', 'contacts', 'calendar', 'internal', 'reports', 'profiles', 'quality'],
  ctc: ['dashboard', 'schools', 'network', 'inventory', 'ctc', 'calls', 'cars', 'supervision', 'contacts', 'calendar', 'internal', 'reports', 'profiles', 'quality'],
  gabinete: ['dashboard', 'schools', 'calls', 'contacts', 'cars', 'calendar', 'reports'],
  dirigente: ['dashboard', 'schools', 'calls', 'contacts', 'cars', 'calendar', 'reports'],
  seom: ['dashboard', 'schools', 'contacts', 'cars', 'calendar', 'reports'],
  sefisc: ['dashboard', 'cars', 'calendar'], segre: ['dashboard', 'cars', 'calendar'], sevesc: ['dashboard', 'cars', 'calendar'], semat: ['dashboard', 'cars', 'calendar'], sepes: ['dashboard', 'cars', 'calendar'], sefrep: ['dashboard', 'cars', 'calendar'], seape: ['dashboard', 'cars', 'calendar'], seafim: ['dashboard', 'cars', 'calendar'], sefin: ['dashboard', 'cars', 'calendar'], secomse: ['dashboard', 'cars', 'calendar'], carros: ['dashboard', 'cars', 'calendar'],
  pedagogico: ['dashboard', 'schools', 'supervision', 'contacts', 'calendar'], consulta: ['dashboard', 'schools', 'contacts', 'calendar']
};

const OFFICIAL_SOURCE_FIXES = {
  inventory: { label: 'Equipamentos', type: 'powerbi-embed', url: '', status: 'replaced', metadata: { domain: 'Equipamentos', source: 'powerbi-embed', autoLoad: false } },
  satisfaction: { label: 'Pesquisa de Satisfação Presencial', type: 'powerbi-embed', url: '', status: 'replaced', metadata: { domain: 'Pesquisa de Satisfação Presencial', source: 'powerbi-embed', autoLoad: false } }
};

function normalize(value) { return String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim(); }
function json(payload, status = 200, headers = {}) { return new Response(JSON.stringify(payload), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', ...headers } }); }
function fail(statusCode, message, metadata = {}) { const error = new Error(message); error.statusCode = statusCode; error.metadata = metadata; return error; }
function errorResponse(error) { return json({ ok: false, error: error.message || 'Erro interno.' }, error.statusCode || 500, error.metadata?.code ? { 'X-PainelURE-Error': error.metadata.code } : {}); }
function args(values) { return values.map(value => value === undefined ? null : value); }
function stmt(db, sql, values = []) { return db.prepare(sql).bind(...args(values)); }
async function first(db, sql, values = []) { return stmt(db, sql, values).first(); }
async function all(db, sql, values = []) { return (await stmt(db, sql, values).all()).results || []; }
async function run(db, sql, values = []) { return stmt(db, sql, values).run(); }
function parseJson(value, fallback = {}) { if (value && typeof value === 'object') return value; try { return value ? JSON.parse(value) : fallback; } catch { return fallback; } }

async function readBody(request) {
  if (!['POST', 'PUT', 'PATCH', 'DELETE'].includes(request.method)) return {};
  const text = await request.text(); if (text.length > 8 * 1024 * 1024) throw fail(413, 'Payload muito grande.');
  if (!text) return {};
  try { return JSON.parse(text); } catch { return { __raw: text }; }
}

function randomHex(bytes = 24) { const data = new Uint8Array(bytes); crypto.getRandomValues(data); return [...data].map(value => value.toString(16).padStart(2, '0')).join(''); }
function hex(buffer) { return [...new Uint8Array(buffer)].map(value => value.toString(16).padStart(2, '0')).join(''); }
function bytesFromHex(text) { const result = new Uint8Array(text.length / 2); for (let i = 0; i < result.length; i++) result[i] = Number.parseInt(text.slice(i * 2, i * 2 + 2), 16); return result; }
async function hashPassword(password, salt = randomHex(16)) { const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(String(password)), 'PBKDF2', false, ['deriveBits']); const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt: bytesFromHex(salt), iterations: 120000, hash: 'SHA-256' }, key, 256); return `pbkdf2$${salt}$${hex(bits)}`; }
async function verifyPassword(password, storedHash) { const [method, salt, expected] = String(storedHash || '').split('$'); if (method !== 'pbkdf2' || !salt || !expected) return false; const actual = (await hashPassword(password, salt)).split('$')[2]; if (actual.length !== expected.length) return false; let difference = 0; for (let i = 0; i < actual.length; i++) difference |= actual.charCodeAt(i) ^ expected.charCodeAt(i); return difference === 0; }

function rowUser(row) { return row ? { ...row, preferences: parseJson(row.preferences, {}) } : null; }
function publicUser(user) { if (!user) return null; const preferences = user.preferences || {}; return { id: user.id, username: user.username, name: user.name, role: user.role, contactId: user.contact_id || user.contactId || '', avatar: user.avatar || '', pin: preferences.pin || '', preferences }; }
function bearerToken(request) { const value = request.headers.get('Authorization') || ''; return value.startsWith('Bearer ') ? value.slice(7) : ''; }
async function authForRequest(request, env) { const token = bearerToken(request); if (!token || !env.DB) return { session: null, user: null }; const session = await first(env.DB, 'SELECT token, user_id, role, created_at FROM sessions WHERE token = ? AND expires_at > ?', [token, new Date().toISOString()]); const user = session?.user_id ? rowUser(await first(env.DB, 'SELECT * FROM users WHERE id = ?', [session.user_id])) : null; return { session: session ? { ...session, token } : null, user }; }
async function requireAuth(request, env) { const auth = await authForRequest(request, env); if (!auth.session) throw fail(401, 'Não autorizado.'); return auth; }
function isAdmin(auth) { return normalize(auth.user?.role || auth.session?.role || '').includes('administrador'); }
function effectiveUser(auth) { return auth.user || (auth.session ? { role: auth.session.role || 'Consulta', name: 'Sessão admin' } : null); }
async function requireAdmin(request, env, message = 'Apenas administrador pode executar esta ação.') { const auth = await requireAuth(request, env); if (!isAdmin(auth)) throw fail(403, message); return auth; }
async function requireInternalWriter(request, env) { const auth = await requireAuth(request, env); const role = normalize(auth.user?.role || auth.session?.role || ''); if (!role.includes('administrador') && !role.includes('seintec') && role !== 'ctc' && !role.includes('tecnicos ctc')) throw fail(403, 'Apenas Administrador, SEINTEC ou CTC pode salvar os dados do café.'); return auth; }

async function findUserByUsername(db, username) { const clean = String(username || '').trim().toLowerCase(); if (!clean) return null; const exact = await first(db, 'SELECT * FROM users WHERE username = ?', [clean]); if (exact) return rowUser(exact); const users = (await all(db, 'SELECT * FROM users ORDER BY name')).map(rowUser); return users.find(user => String(user.name || '').trim().split(/\s+/)[0]?.toLowerCase() === clean || String(user.username || '').toLowerCase().startsWith(`${clean}.`)) || null; }
async function createSession(db, user = null) { const token = randomHex(24); const now = new Date(); const expires = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000); await run(db, 'INSERT INTO sessions (token, user_id, role, created_at, expires_at) VALUES (?, ?, ?, ?, ?)', [token, user?.id || null, user?.role || 'Administrador', now.toISOString(), expires.toISOString()]); return token; }

async function readStore(db) { const row = await first(db, 'SELECT payload, source, updated_at FROM app_state WHERE id = ?', ['main']); if (!row) return { version: 1, source: 'd1', updatedAt: null, appData: {} }; const payload = parseJson(row.payload, {}); return { ...payload, source: row.source || payload.source || 'd1', updatedAt: row.updated_at || payload.updatedAt || null }; }
async function saveStore(db, appData, source = 'api', options = {}) { const current = await readStore(db); if (!options.force && current.updatedAt && String(options.baseUpdatedAt || '') !== current.updatedAt) throw fail(409, 'Estado online mais novo encontrado. Recarregue antes de salvar.', { code: 'STALE_APP_STATE', currentUpdatedAt: current.updatedAt, baseUpdatedAt: options.baseUpdatedAt || '' }); const payload = { version: 1, source, updatedAt: new Date().toISOString(), appData: appData || {} }; await db.batch([stmt(db, 'INSERT INTO app_state (id, payload, source, updated_at) VALUES (?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload, source=excluded.source, updated_at=excluded.updated_at', ['main', JSON.stringify(payload), source, payload.updatedAt]), stmt(db, 'INSERT INTO app_snapshots (id, payload, source, created_at) VALUES (?, ?, ?, ?)', [crypto.randomUUID(), JSON.stringify(payload), source, payload.updatedAt])]); return payload; }

function accessForRole(role, appData = {}) { const target = normalize(role); const custom = appData?.accessRules?.roleAccess || {}; const key = Object.keys(DATA_ACCESS).find(item => normalize(item) === target) || (target.includes('admin') ? 'administrador' : target.includes('supervis') ? 'supervisao' : target.includes('ctc') ? 'tecnicos ctc' : target.includes('seintec') ? 'seintec' : target.includes('setec') ? 'setec' : target.includes('gabinete') ? 'gabinete' : target.includes('dirigente') ? 'dirigente' : target.includes('carro') ? 'carros' : target.includes('pedag') ? 'pedagogico' : 'consulta'); const saved = custom[key] || custom[role]; return [...new Set([...(DATA_ACCESS[key] || DATA_ACCESS.consulta), ...(Array.isArray(saved) ? saved : [])])]; }
function canAccessData(page, user, appData) { if (['satisfaction', 'satisfaction-online'].includes(page)) return normalize(user?.role || '').includes('administrador'); if (page === 'network') return true; const access = accessForRole(user?.role || 'Consulta', appData); return page === 'calls' || page === 'ctc' ? access.includes('calls') || access.includes('ctc') : access.includes(page); }
function identityMatches(firstValue, secondValue) { const a = normalize(firstValue).replace(/[._-]+/g, ' '); const b = normalize(secondValue).replace(/[._-]+/g, ' '); if (!a || !b) return false; if (a.includes('@') || b.includes('@')) return a.split('@')[0] === b.split('@')[0]; const at = a.split(/\s+/).filter(Boolean); const bt = b.split(/\s+/).filter(Boolean); return a === b || (at.length >= 2 && at.every(value => bt.includes(value))) || (bt.length >= 2 && bt.every(value => at.includes(value))); }
function supervisorForUser(appData, user) { if (!user || !normalize(user.role).includes('supervis')) return null; const values = [user.name, user.username, user.email, user.contactName, user.supervisorName, user.preferences?.supervisorName].filter(Boolean); return (appData.supervisors || []).find(item => [item.name, item.email, item.login, item.username, ...(item.aliases || [])].filter(Boolean).some(value => values.some(candidate => identityMatches(candidate, value)))) || null; }
function canViewCredentials(user) { const role = normalize(user?.role || ''); return ['administrador', 'tecnicos ctc', 'setec', 'seintec'].some(value => role.includes(value)); }
function publicCarBooking(item) { return { requestId: item.requestId || item.id || '', vehicle: item.vehicle || item.car || item.recurso || 'Carro oficial', date: item.date || item.value || '', time: item.time || item.hora || '', returnTime: item.returnTime || item.devolutionTime || item.devolucao || '', status: item.status || 'reservado', restricted: true }; }
function canViewCarBookingDetails(item, user) { const role = normalize(user?.role || ''); if (['administrador', 'gabinete', 'dirigente', 'seom', 'setec', 'seintec', 'ctc'].some(value => role.includes(value))) return true; const userKeys = [user?.role, user?.sector, user?.setor, user?.contactRole].map(normalize).filter(Boolean); const itemKeys = [item?.requester, item?.sector, item?.setor, item?.category, item?.owner].map(normalize).filter(Boolean); return userKeys.some(value => itemKeys.some(key => key === value || key.includes(value) || value.includes(key))); }
function scopedStore(store, user) { const appData = store.appData || {}; const supervisorScope = normalize(user?.role).includes('supervis'); const supervisor = supervisorForUser(appData, user); const allowed = new Set((supervisor?.assignedSchools || []).map(normalize)); const scopedItems = (items, field = 'school') => supervisorScope ? (items || []).filter(item => allowed.has(normalize(item?.[field]))) : (items || []); const scopedObject = source => supervisorScope ? Object.fromEntries(Object.entries(source || {}).filter(([school]) => allowed.has(normalize(school)))) : (source || {}); const schools = supervisorScope ? (appData.schools || []).filter(item => allowed.has(normalize(item.name))) : (appData.schools || []); const network = scopedObject(appData.networkData); const safeNetwork = canViewCredentials(user) ? network : Object.fromEntries(Object.entries(network).map(([key, value]) => { const { credentials, ...safe } = value || {}; return [key, safe]; })); return { ...appData, schools: canAccessData('schools', user, appData) ? schools : [], supervisors: canAccessData('supervision', user, appData) ? (supervisorScope ? (supervisor ? [supervisor] : []) : (appData.supervisors || [])) : [], networkData: canAccessData('network', user, appData) ? safeNetwork : {}, schoolInventoryMetrics: canAccessData('inventory', user, appData) ? scopedObject(appData.schoolInventoryMetrics) : {}, schoolProfiles: canAccessData('schools', user, appData) ? scopedItems(appData.schoolProfiles) : [], schoolAssets: canAccessData('inventory', user, appData) ? scopedItems(appData.schoolAssets) : [], inventory: canAccessData('inventory', user, appData) ? scopedItems(appData.inventory) : [], calls: canAccessData('calls', user, appData) ? scopedItems(appData.calls) : [], ctcVisits: canAccessData('ctc', user, appData) ? scopedItems(appData.ctcVisits, 'place') : [], contacts: canAccessData('contacts', user, appData) ? (appData.contacts || []) : [], cars: canAccessData('cars', user, appData) ? (appData.cars || []).map(item => canViewCarBookingDetails(item, user) ? item : publicCarBooking(item)) : [], calendar: canAccessData('calendar', user, appData) ? (appData.calendar || []) : [], satisfaction: canAccessData('satisfaction', user, appData) ? (appData.satisfaction || []) : [], internal: canAccessData('internal', user, appData) ? (appData.internal || []) : [], reports: canAccessData('reports', user, appData) ? (appData.reports || []) : [], profiles: canAccessData('profiles', user, appData) ? (appData.profiles || []) : [], quality: canAccessData('quality', user, appData) ? (appData.quality || []) : [], users: canAccessData('admin', user, appData) ? (appData.users || []) : [], adminChecks: canAccessData('admin', user, appData) ? (appData.adminChecks || []) : [], accessRules: appData.accessRules || {}, pageMaintenance: appData.pageMaintenance || {} }; }

function normalizeHeader(value) { return normalize(value).replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, ''); }
function parseCsvLine(line, delimiter) { const cells = []; let cell = ''; let quoted = false; for (let i = 0; i < line.length; i++) { const char = line[i]; const next = line[i + 1]; if (char === '"' && quoted && next === '"') { cell += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === delimiter && !quoted) { cells.push(cell.trim()); cell = ''; } else cell += char; } cells.push(cell.trim()); return cells; }
function parseCsv(text) { const lines = String(text || '').replace(/^\uFEFF/, '').split(/\r?\n/).filter(line => line.trim()); if (!lines.length) return []; const delimiter = (lines[0].match(/;/g) || []).length > (lines[0].match(/,/g) || []).length ? ';' : ','; const counts = {}; const headers = parseCsvLine(lines[0], delimiter).map(header => { const base = normalizeHeader(header) || 'col'; counts[base] = (counts[base] || 0) + 1; return counts[base] === 1 ? base : `${base}_${counts[base]}`; }); return lines.slice(1).map(line => parseCsvLine(line, delimiter).reduce((row, value, index) => ({ ...row, [headers[index]]: value || '' }), {})); }
function valueOf(row, keys, fallback = '') { for (const key of keys) { const actual = row[key] !== undefined ? row[key] : Object.entries(row || {}).find(([name]) => normalizeHeader(name) === normalizeHeader(key))?.[1]; if (actual !== undefined && actual !== null && String(actual).trim()) return typeof actual === 'object' ? String(actual.Title || actual.Name || actual.LookupValue || actual.value || '') : String(actual).trim(); } return fallback; }
function numberOf(row, keys, fallback = 0) { const text = valueOf(row, keys, ''); const value = Number(String(text).replace(/\./g, '').replace(',', '.')); return Number.isFinite(value) ? value : fallback; }
function normalizeRows(type, rows) {
  if (type === 'schools') return rows.map(row => { const name = valueOf(row, ['escola', 'nome', 'unidade', 'name'], 'Escola sem nome'); return { name, city: valueOf(row, ['municipio', 'cidade', 'city']), cie: valueOf(row, ['cie', 'codigo', 'codigo_cie']), initials: valueOf(row, ['iniciais', 'initials'], name.split(/\s+/).map(value => value[0]).join('').slice(0, 2).toUpperCase()), fiche: numberOf(row, ['ficha', 'ficha_pct', 'percentual']), items: numberOf(row, ['itens', 'items', 'inventario']), status: normalize(valueOf(row, ['status'], 'ok')).includes('aten') ? 'warn' : 'ok' }; });
  if (type === 'contacts') return rows.map(row => ({ name: valueOf(row, ['nome', 'name', 'contato', 'responsavel'], 'Sem nome'), role: valueOf(row, ['cargo', 'funcao', 'role', 'descricao'], 'Contato'), sector: valueOf(row, ['setor', 'categoria', 'departamento', 'area'], 'Tecnologia'), email: valueOf(row, ['email', 'e_mail', 'mail']), phone: valueOf(row, ['ramal', 'telefone', 'whatsapp', 'celular']) }));
  if (type === 'calendar') return rows.map(row => ({ label: valueOf(row, ['titulo', 'evento', 'label', 'nome'], 'Evento'), value: valueOf(row, ['data', 'quando', 'date', 'value'], 'sem data'), note: valueOf(row, ['observacao', 'descricao', 'local', 'note']), tone: valueOf(row, ['status', 'tone', 'tipo'], 'info'), type: valueOf(row, ['tipo', 'type']), scope: valueOf(row, ['escopo', 'scope', 'visibilidade']), owner: valueOf(row, ['responsavel', 'dono', 'owner', 'usuario', 'user']), assignee: valueOf(row, ['atribuido', 'assignee', 'destinatario']), contactId: valueOf(row, ['contact_id', 'id_contato', 'contato_id']), ownerId: valueOf(row, ['owner_id', 'user_id', 'id_usuario']), ownerEmail: valueOf(row, ['owner_email', 'email_usuario', 'email']) }));
  if (type === 'cars') return rows.map(row => ({ requestId: valueOf(row, ['id']), vehicle: valueOf(row, ['carro', 'veiculo', 'vehicle', 'recurso', 'title'], 'Carro oficial'), date: valueOf(row, ['data', 'data_da_reserva', 'data_reserva', 'date', 'quando']), time: valueOf(row, ['hora', 'horario', 'time']), returnTime: valueOf(row, ['data_devolucao', 'devolucao', 'return_time']), requester: valueOf(row, ['setor', 'categoria', 'solicitante', 'responsavel', 'requester', 'owner']), sector: valueOf(row, ['setor', 'categoria', 'area', 'departamento']), destination: valueOf(row, ['localexterno', 'local_externo', 'destino', 'local', 'destination', 'place', 'escolas', 'motivo', 'objetivo']), driver: valueOf(row, ['nome_condutor', 'condutor_nome', 'motorista', 'driver', 'condutor']), status: valueOf(row, ['status', 'situacao', 'tone'], 'pendente'), note: valueOf(row, ['observacao', 'observacoes', 'descricao', 'note', 'motivo']), sourceFields: Object.keys(row).sort() }));
  if (type === 'satisfaction') return rows.map(row => ({ title: valueOf(row, ['motivo', 'descricao', 'titulo', 'pesquisa', 'campanha', 'title', 'nome'], 'Pesquisa de satisfação'), audience: valueOf(row, ['id'], '') ? `Atendimento #${valueOf(row, ['id'])}` : 'Atendimento URE', status: valueOf(row, ['status', 'situacao', 'andamento'], 'respondida'), score: valueOf(row, ['avaliacao_atendimento', 'avaliacao', 'nota', 'media', 'score', 'satisfacao']), responses: 1, link: valueOf(row, ['link', 'url', 'formulario', 'forms']), period: valueOf(row, ['data_atendimento', 'data', 'periodo', 'competencia']), note: valueOf(row, ['observacao', 'observacoes', 'note']) }));
  if (type === 'inventory') return rows.map(row => { const school = valueOf(row, ['escola', 'school', 'unidade'], 'Escola sem nome'); const name = valueOf(row, ['tipo', 'equipamento', 'item', 'nome'], 'Item'); const status = normalize(valueOf(row, ['status', 'situacao', 'estado'], 'ok')); return { id: valueOf(row, ['id']) ? `sharepoint-inventory-${valueOf(row, ['id'])}` : undefined, school, name, sourceName: name, notes: Object.entries(row).filter(([, value]) => String(value || '').trim()).map(([key, value]) => `${key}: ${value}`).join(' | '), status: status.includes('defeito') || status.includes('quebrado') ? 'defeito' : status.includes('manut') ? 'manutencao' : 'ok' }; });
  if (type === 'network') return rows.reduce((result, row) => { const school = valueOf(row, ['escola', 'unidade', 'nome', 'school'], 'Escola sem nome'); const item = result[school] || { network: [], ips: [], cameras: [], credentials: ['Acesso restrito', 'Não publicado no frontend estático', 'Solicitar ao CTC, SETEC ou SEINTEC'] }; for (const [field, keys] of Object.entries({ network: ['rede', 'network', 'gateway', 'wifi'], ips: ['ip', 'ips', 'cie', 'banda'], cameras: ['camera', 'cameras', 'dvr'] })) { const value = valueOf(row, keys); if (value && !item[field].includes(value)) item[field].push(value); } result[school] = item; return result; }, {});
  if (type === 'supervision') { const stats = new Map(); rows.forEach(row => { const name = valueOf(row, ['nome_do_supervisor', 'supervisor', 'nome'], 'Supervisor'); const schools = Object.entries(row).filter(([key, value]) => (key.startsWith('escola_visitada') || key.startsWith('escolas_visitadas')) && String(value || '').trim()).map(([, value]) => String(value).trim()); const item = stats.get(name) || { name, visits: 0, schools: new Set() }; schools.forEach(school => item.schools.add(school)); item.visits += schools.length || 1; stats.set(name, item); }); return [...stats.values()].map(item => ({ name: item.name, email: '', phone: '', schools: item.schools.size, assignedSchools: [...item.schools], week: '0/3', month: `${item.visits}/${Math.max(3, item.schools.size * 3)}`, pending: Math.max(0, Math.max(3, item.schools.size * 3) - item.visits), visits: item.visits, visitedSchools: item.schools.size, source: 'Importação backend' })); }
  return rows;
}

function officialSourceCsvUrl(source) { const raw = String(source?.url || '').trim(); const gid = String(source?.metadata?.gid || source?.metadata?.panelGid || '').trim(); if (!gid || !/docs\.google\.com\/spreadsheets\/d\//i.test(raw)) return raw; const published = raw.match(/docs\.google\.com\/spreadsheets\/d\/e\/([^/]+)/i); if (published) return `https://docs.google.com/spreadsheets/d/e/${published[1]}/pub?output=csv&single=true&gid=${encodeURIComponent(gid)}`; const regular = raw.match(/docs\.google\.com\/spreadsheets\/d\/([^/]+)/i); return regular ? `https://docs.google.com/spreadsheets/d/${regular[1]}/export?format=csv&gid=${encodeURIComponent(gid)}` : raw; }
function assertSharePointUrl(value) { const url = new URL(value); if (url.hostname !== 'seesp-my.sharepoint.com') throw new Error('Apenas links seesp-my.sharepoint.com são aceitos.'); return url; }
function rememberCookies(jar, response) { const header = response.headers.get('set-cookie') || ''; header.split(/,(?=\s*[^;,=\s]+=[^;,]+)/).forEach(value => { const pair = value.split(';')[0]; const index = pair.indexOf('='); if (index > 0) jar.set(pair.slice(0, index), pair.slice(index + 1)); }); }
async function fetchWithCookies(url, jar, options = {}, redirects = 8) { const headers = new Headers(options.headers || {}); if (jar.size) headers.set('Cookie', [...jar].map(([key, value]) => `${key}=${value}`).join('; ')); const response = await fetch(url, { ...options, headers, redirect: 'manual' }); rememberCookies(jar, response); const location = response.headers.get('location'); if ([301, 302, 303, 307, 308].includes(response.status) && location && redirects > 0) return fetchWithCookies(new URL(location, url).toString(), jar, options, redirects - 1); return response; }
async function fetchSharePointRows(sourceUrl) { const parsed = assertSharePointUrl(sourceUrl); const jar = new Map(); const pageResponse = await fetchWithCookies(parsed.toString(), jar, { headers: { Accept: 'text/html,application/xhtml+xml' } }); const html = await pageResponse.text(); if (!pageResponse.ok) throw new Error(`SharePoint respondeu ${pageResponse.status} ao abrir o link.`); if (/Sign in to your account/i.test(html)) throw new Error('O link do SharePoint abriu tela de login. Use um link compartilhado anônimo da lista.'); const contextListUrl = html.match(/"listUrl":"([^"]+)"/)?.[1]?.replace(/\\\//g, '/'); const direct = parsed.pathname.match(/^(.*)\/Lists\/([^/]+)\/AllItems\.aspx$/i); const listPath = contextListUrl || (direct ? `${decodeURIComponent(direct[1])}/Lists/${decodeURIComponent(direct[2])}` : ''); if (!listPath) throw new Error('Não foi possível identificar a lista do SharePoint.'); const sitePath = listPath.split('/Lists/')[0]; const escaped = listPath.replace(/'/g, "''"); const apiUrl = `${parsed.origin}${sitePath}/_api/web/GetList('${escaped}')/items?$top=5000&$expand=FieldValuesAsText`; const apiResponse = await fetchWithCookies(apiUrl, jar, { headers: { Accept: 'application/json;odata=nometadata' } }); const text = await apiResponse.text(); if (!apiResponse.ok) throw new Error(`SharePoint API respondeu ${apiResponse.status}: ${text.slice(0, 180)}`); const payload = JSON.parse(text); return Array.isArray(payload.value) ? payload.value : []; }
async function fetchSourceRows(source) { if (String(source.type || '').toLowerCase() === 'sharepoint-list') return fetchSharePointRows(source.url); const response = await fetch(officialSourceCsvUrl(source), { headers: { Accept: 'text/csv,text/plain,*/*', 'User-Agent': 'PainelURE-Cloudflare/1.0' } }); const text = await response.text(); if (!response.ok) throw new Error(`Fonte respondeu ${response.status}.`); return parseCsv(text); }
function sourceWithFixes(rows) { const map = new Map(rows.map(item => [item.key, item])); for (const [key, fix] of Object.entries(OFFICIAL_SOURCE_FIXES)) map.set(key, { ...(map.get(key) || { key }), ...fix, key, metadata: { ...(map.get(key)?.metadata || {}), ...fix.metadata }, updatedAt: map.get(key)?.updatedAt || new Date().toISOString() }); return [...map.values()].sort((a, b) => String(a.key).localeCompare(String(b.key))); }
async function listSources(db) { const rows = await all(db, 'SELECT key, label, type, url, status, metadata, updated_at FROM official_sources ORDER BY key'); return sourceWithFixes(rows.map(row => ({ key: row.key, label: row.label, type: row.type, url: row.url, status: row.status, monthKey: parseJson(row.metadata, {}).monthKey || '', metadata: parseJson(row.metadata, {}), updatedAt: row.updated_at }))); }
async function saveSources(db, input) { const sourceMap = Array.isArray(input) ? Object.fromEntries(input.map(item => [item.key, item])) : (input || {}); const entries = Object.entries(sourceMap).map(([key, source]) => ({ key, label: String(source.label || key), type: String(source.type || 'csv'), url: String(source.url || ''), status: String(source.status || (source.url ? 'configured' : 'pending')), metadata: { ...(source.metadata || {}), ...(source.monthKey || source.metadata?.monthKey ? { monthKey: source.monthKey || source.metadata?.monthKey } : {}) } })); await db.batch(entries.map(source => stmt(db, 'INSERT INTO official_sources (key, label, type, url, status, metadata, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT(key) DO UPDATE SET label=excluded.label, type=excluded.type, url=excluded.url, status=excluded.status, metadata=excluded.metadata, updated_at=excluded.updated_at', [source.key, source.label, source.type, source.url, source.status, JSON.stringify(source.metadata), new Date().toISOString()]))); return listSources(db); }
async function audit(db, auth, action, entity, entityId = '', detail = '', metadata = {}) { await run(db, 'INSERT INTO audit_events (id, user_id, actor_name, actor_role, action, entity, entity_id, detail, metadata, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [crypto.randomUUID(), auth.user?.id || null, auth.user?.name || (auth.session ? 'Sessão admin' : ''), auth.user?.role || auth.session?.role || '', action, entity, entityId, detail, JSON.stringify(metadata), new Date().toISOString()]); }
async function refreshSources(db, keys) { const selected = new Set(Array.isArray(keys) ? keys.filter(Boolean) : []); const sources = await listSources(db); const targets = sources.filter(source => (!selected.size || selected.has(source.key)) && source.url); const store = await readStore(db); const appData = { ...(store.appData || {}) }; const results = []; for (const source of targets) { try { const rows = await fetchSourceRows(source); const normalized = normalizeRows(source.key, rows); if (source.key === 'network') appData.networkData = normalized; else if (source.key === 'inventory') appData.schoolAssets = normalized; else if (source.key === 'supervision') appData.supervisors = normalized; else appData[source.key] = normalized; await run(db, 'INSERT INTO import_runs (id, source_key, rows_count, status, detail, created_at) VALUES (?, ?, ?, ?, ?, ?)', [crypto.randomUUID(), source.key, rows.length, 'ok', `${source.key} atualizado pela fonte oficial`, new Date().toISOString()]); results.push({ key: source.key, status: 'loaded', rows: rows.length }); } catch (error) { await run(db, 'INSERT INTO import_runs (id, source_key, rows_count, status, detail, created_at) VALUES (?, ?, ?, ?, ?, ?)', [crypto.randomUUID(), source.key, 0, 'error', error.message, new Date().toISOString()]); results.push({ key: source.key, status: 'error', rows: 0, error: error.message }); } } const data = results.some(item => item.status === 'loaded') ? await saveStore(db, appData, 'official-sources', { force: true }) : store; return { results, data }; }

async function updateUser(db, current, patch) { const next = { ...current, name: patch.name !== undefined ? String(patch.name).trim() : current.name, role: patch.role !== undefined ? String(patch.role).trim() : current.role, contact_id: patch.contactId !== undefined ? String(patch.contactId || '').trim() : current.contact_id || '', avatar: patch.avatar !== undefined ? String(patch.avatar || '') : current.avatar || '', preferences: patch.preferences !== undefined ? patch.preferences || {} : current.preferences || {} }; if (patch.password) { next.password_hash = await hashPassword(patch.password); next.preferences = { ...next.preferences, pin: String(patch.password) }; } await run(db, 'UPDATE users SET name=?, role=?, contact_id=?, password_hash=?, avatar=?, preferences=?, updated_at=? WHERE id=?', [next.name, next.role, next.contact_id, next.password_hash || current.password_hash, next.avatar, JSON.stringify(next.preferences), new Date().toISOString(), current.id]); return next; }

async function apiHandler(request, env, body) {
  if (!env.DB) throw fail(503, 'Binding D1 (DB) não configurado.');
  const url = new URL(request.url); const path = url.pathname.split('/').filter(Boolean); const method = request.method;
  if ((url.pathname === '/api/health' || url.pathname === '/health') && method === 'GET') { const row = await first(env.DB, 'SELECT source, updated_at FROM app_state WHERE id = ?', ['main']); return { ok: true, name: 'PainelURE API Cloudflare', time: new Date().toISOString(), storage: { mode: 'cloudflare-d1', ready: true, updatedAt: row?.updated_at || null, source: row?.source || null, error: null } }; }
  if (url.pathname === '/api/auth/login' && method === 'POST') { const username = String(body.username || '').trim(); const password = String(body.password || ''); if (username) { const user = await findUserByUsername(env.DB, username); const valid = user && (normalize(user.role).includes('supervis') || (user.preferences?.pin ? password === String(user.preferences.pin) : await verifyPassword(password, user.password_hash))); if (!valid) throw fail(401, 'Usuário ou senha inválidos.'); const token = await createSession(env.DB, user); await run(env.DB, 'UPDATE users SET preferences = ?, updated_at = ? WHERE id = ?', [JSON.stringify({ ...(user.preferences || {}), lastLoginAt: new Date().toISOString() }), new Date().toISOString(), user.id]); return { ok: true, token, user: publicUser(user) }; } if (!env.PAINELURE_ADMIN_KEY || body.key !== env.PAINELURE_ADMIN_KEY) throw fail(401, 'Chave inválida.'); return { ok: true, token: await createSession(env.DB), user: null }; }
  if (url.pathname === '/api/auth/me' && method === 'GET') { const auth = await requireAuth(request, env); return { ok: true, user: publicUser(auth.user), session: auth.session }; }
  if (url.pathname === '/api/auth/logout' && method === 'POST') { const token = bearerToken(request); if (token) await run(env.DB, 'DELETE FROM sessions WHERE token = ?', [token]); return { ok: true }; }
  if (url.pathname === '/api/users' && method === 'GET') { await requireAdmin(request, env, 'Apenas administrador pode listar usuários.'); return { ok: true, users: (await all(env.DB, 'SELECT id, username, name, role, contact_id, avatar, preferences FROM users ORDER BY name')).map(rowUser).map(publicUser) }; }
  if (url.pathname === '/api/users' && method === 'POST') { await requireAdmin(request, env, 'Apenas administrador pode criar usuários.'); const password = String(body.password || randomHex(12)); const user = { id: crypto.randomUUID(), username: String(body.username || '').trim().toLowerCase(), name: String(body.name || body.username || 'Usuário').trim(), role: String(body.role || 'Consulta').trim(), contactId: String(body.contactId || body.contact_id || '').trim(), passwordHash: await hashPassword(password), avatar: String(body.avatar || ''), preferences: { ...(body.preferences || {}), pin: body.pin || password } }; if (!user.username) throw fail(400, 'Usuário obrigatório.'); try { await run(env.DB, 'INSERT INTO users (id, username, name, role, contact_id, password_hash, avatar, preferences, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [user.id, user.username, user.name, user.role, user.contactId, user.passwordHash, user.avatar, JSON.stringify(user.preferences), new Date().toISOString(), new Date().toISOString()]); } catch { throw fail(409, 'Usuário já existe.'); } return { ok: true, user: publicUser({ ...user, contact_id: user.contactId, password_hash: user.passwordHash }) }; }
  if (url.pathname === '/api/users/me' && method === 'PUT') { const auth = await requireAuth(request, env); if (!auth.user) throw fail(400, 'Sessão sem usuário vinculado.'); return { ok: true, user: publicUser(await updateUser(env.DB, auth.user, body)) }; }
  if (path[0] === 'api' && path[1] === 'users' && path.length === 3 && ['PUT', 'DELETE'].includes(method)) { await requireAdmin(request, env, 'Apenas administrador pode alterar usuários.'); const user = rowUser(await first(env.DB, 'SELECT * FROM users WHERE id = ?', [decodeURIComponent(path[2])])); if (!user) throw fail(404, 'Usuário não encontrado.'); if (method === 'DELETE') { await run(env.DB, 'DELETE FROM sessions WHERE user_id = ?', [user.id]); await run(env.DB, 'DELETE FROM users WHERE id = ?', [user.id]); return { ok: true, user: publicUser(user) }; } return { ok: true, user: publicUser(await updateUser(env.DB, user, body)) }; }
  if (url.pathname === '/api/sources' && method === 'GET') return { ok: true, sources: await listSources(env.DB) };
  if (url.pathname === '/api/sources' && method === 'PUT') { const auth = await requireAdmin(request, env); const sources = await saveSources(env.DB, body.sources || body); await audit(env.DB, auth, 'update', 'sources', 'official', 'Fontes oficiais atualizadas.', { count: sources.length }); return { ok: true, sources }; }
  if (url.pathname === '/api/sources/refresh' && method === 'POST') { const auth = await requireAdmin(request, env); const result = await refreshSources(env.DB, body.keys || []); await audit(env.DB, auth, 'refresh', 'official_sources', 'all', 'Fontes oficiais atualizadas.', { results: result.results }); return { ok: true, ...result, storage: { mode: 'cloudflare-d1', ready: true } }; }
  if (url.pathname === '/api/sharepoint-list' && method === 'GET') { const rows = await fetchSharePointRows(url.searchParams.get('url') || ''); return { ok: true, rows, rowsCount: rows.length }; }
  if (url.pathname === '/api/data' && method === 'GET') { const auth = await requireAuth(request, env); const store = await readStore(env.DB); return { ok: true, data: { ...store, appData: scopedStore(store, effectiveUser(auth)) }, storage: { mode: 'cloudflare-d1', ready: true, updatedAt: store.updatedAt, source: store.source, error: null } }; }
  if (url.pathname === '/api/data' && method === 'PUT') { const auth = await requireAdmin(request, env); const data = await saveStore(env.DB, body.appData || body, 'api', { baseUpdatedAt: body.baseUpdatedAt || '', force: body.force === true }); await audit(env.DB, auth, 'update', 'app_state', 'main', 'Estado do app atualizado.'); return { ok: true, data, storage: { mode: 'cloudflare-d1', ready: true, updatedAt: data.updatedAt, source: data.source, error: null } }; }
  if (url.pathname === '/api/internal' && method === 'PUT') { const auth = await requireInternalWriter(request, env); const store = await readStore(env.DB); const data = await saveStore(env.DB, { ...(store.appData || {}), internal: body.internal && typeof body.internal === 'object' ? body.internal : {} }, 'internal', { force: true }); await audit(env.DB, auth, 'update', 'internal', 'cafe', 'Dados internos do café atualizados.'); return { ok: true, data, storage: { mode: 'cloudflare-d1', ready: true } }; }
  if (url.pathname === '/api/supervision/justification' && method === 'PUT') { const auth = await requireAuth(request, env); const name = String(body.supervisorName || '').trim(); const month = String(body.monthKey || '').trim(); if (!name || !/^\d{4}-\d{2}$/.test(month)) throw fail(400, 'Supervisor e mês são obrigatórios.'); const store = await readStore(env.DB); const supervisors = [...(store.appData?.supervisors || [])]; const index = supervisors.findIndex(item => normalize(item.name) === normalize(name) || (body.supervisorEmail && normalize(item.email) === normalize(body.supervisorEmail))); if (index < 0) throw fail(404, 'Supervisor não encontrado.'); if (!isAdmin(auth) && normalize(supervisorForUser(store.appData, auth.user)?.name) !== normalize(supervisors[index].name)) throw fail(403, 'Você só pode editar a própria justificativa.'); const justifications = { ...(supervisors[index].justifications || {}) }; if (String(body.justification || '').trim()) justifications[month] = String(body.justification).trim().slice(0, 2000); else delete justifications[month]; supervisors[index] = { ...supervisors[index], justifications }; const data = await saveStore(env.DB, { ...store.appData, supervisors }, 'supervision:justification', { force: true }); await audit(env.DB, auth, 'update', 'supervision_justification', name, `Justificativa de ${month} atualizada.`); return { ok: true, supervisor: supervisors[index], data: { updatedAt: data.updatedAt } }; }
  if (url.pathname === '/api/mobile/actions' && method === 'POST') { const auth = await requireAuth(request, env); const actor = effectiveUser(auth); const types = new Set(['calls', 'ctcvisits', 'cars', 'calendar', 'inventory']); const type = normalize(body.type); if (!types.has(type) || !body.record || typeof body.record !== 'object' || Array.isArray(body.record)) throw fail(400, 'Tipo e registro operacional são obrigatórios.'); const required = { calls: ['title', 'description'], cars: ['date', 'destination'], calendar: ['date', 'title'], inventory: ['school', 'name'], ctcvisits: ['date', 'place', 'objective'] }; const missing = (required[type] || []).filter(field => !String(body.record[field] || '').trim()); if (missing.length) throw fail(400, `Campos obrigatórios ausentes: ${missing.join(', ')}.`); const permission = type === 'inventory' ? 'inventory' : type === 'ctcvisits' ? 'ctc' : type; const store = await readStore(env.DB); if (!canAccessData(permission, actor, store.appData)) throw fail(403, 'Perfil sem acesso a esta operação.'); const collection = type === 'inventory' ? 'schoolAssets' : type === 'ctcvisits' ? 'ctcVisits' : type; const record = { ...body.record, id: body.record.id || `${type}-${Date.now()}-${randomHex(4)}`, createdAt: body.record.createdAt || new Date().toISOString(), createdBy: body.record.createdBy || actor?.username || actor?.name || 'mobile' }; const data = await saveStore(env.DB, { ...store.appData, [collection]: [...(store.appData[collection] || []), record] }, `mobile:${type}`, { force: true }); await audit(env.DB, auth, 'create', `mobile_${type}`, record.id, `Registro ${type} criado pelo app.`); return { ok: true, type, record, data }; }
  if (url.pathname.startsWith('/api/import/') && method === 'POST') { const auth = await requireAdmin(request, env); const type = path[2]; const rows = Array.isArray(body.rows) ? body.rows : parseCsv(String(body.csv || body.__raw || '')); const normalized = normalizeRows(type, rows); const store = await readStore(env.DB); const field = type === 'inventory' ? 'schoolAssets' : type === 'network' ? 'networkData' : type === 'supervision' ? 'supervisors' : type; const data = await saveStore(env.DB, { ...store.appData, [field]: normalized }, `import:${type}`, { force: true }); await run(env.DB, 'INSERT INTO import_runs (id, source_key, rows_count, status, detail, created_at) VALUES (?, ?, ?, ?, ?, ?)', [crypto.randomUUID(), type, rows.length, 'ok', `${type} importado`, new Date().toISOString()]); await audit(env.DB, auth, 'import', type, type, 'CSV importado pelo backend.', { rows: rows.length }); return { ok: true, rows: rows.length, data, storage: { mode: 'cloudflare-d1', ready: true } }; }
  if (url.pathname === '/api/snapshots' && method === 'GET') { await requireAdmin(request, env); const limit = Math.min(100, Math.max(1, Number(url.searchParams.get('limit') || 20))); return { ok: true, snapshots: (await all(env.DB, 'SELECT id, source, created_at FROM app_snapshots ORDER BY created_at DESC LIMIT ?', [limit])).map(row => ({ id: row.id, source: row.source, createdAt: row.created_at })) }; }
  if (url.pathname === '/api/audit' && method === 'GET') { await requireAdmin(request, env); const limit = Math.min(200, Math.max(1, Number(url.searchParams.get('limit') || 50))); return { ok: true, events: (await all(env.DB, 'SELECT id, actor_name, actor_role, action, entity, entity_id, detail, metadata, created_at FROM audit_events ORDER BY created_at DESC LIMIT ?', [limit])).map(row => ({ id: row.id, actorName: row.actor_name, actorRole: row.actor_role, action: row.action, entity: row.entity, entityId: row.entity_id, detail: row.detail, metadata: parseJson(row.metadata), createdAt: row.created_at })) }; }
  if (url.pathname === '/api/imports' && method === 'GET') { await requireAdmin(request, env); const limit = Math.min(100, Math.max(1, Number(url.searchParams.get('limit') || 20))); return { ok: true, imports: (await all(env.DB, 'SELECT id, source_key, rows_count, status, detail, created_at FROM import_runs ORDER BY created_at DESC LIMIT ?', [limit])).map(row => ({ id: row.id, sourceKey: row.source_key, rowsCount: Number(row.rows_count || 0), status: row.status, detail: row.detail, createdAt: row.created_at })) }; }
  throw fail(404, 'Endpoint não encontrado.');
}

function assetRequest(request) { const url = new URL(request.url); if (url.pathname === '/') url.pathname = '/index.html'; return new Request(url, request); }
export default { async fetch(request, env) { if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Admin-Key', 'Access-Control-Allow-Methods': 'GET, POST, PUT, PATCH, DELETE, OPTIONS' } }); const url = new URL(request.url); try { if (url.pathname.startsWith('/api/') || url.pathname === '/health') return json(await apiHandler(request, env, await readBody(request))); return env.ASSETS.fetch(assetRequest(request)); } catch (error) { return errorResponse(error); } } };
